# Generated by Django 3.0.5 on 2020-04-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='blog',
            name='order',
            field=models.IntegerField(default=500),
        ),
    ]
