# Generated by Django 3.0.5 on 2020-04-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200425_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='order',
        ),
        migrations.AddField(
            model_name='blog',
            name='price',
            field=models.CharField(default=True, max_length=11),
            preserve_default=False,
        ),
    ]
