# Generated by Django 3.0.5 on 2020-04-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200425_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='blog',
            name='image2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='blog_posts/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='blog_posts/'),
        ),
    ]
